
export const itemCharacteristics = {
  version: 23,    
  categories: [
    {name: {EN: 'Bread', FR: 'Pain'}, label: {EN: '', FR: ''}, id2: 'B', expiration: '1', expirationMinusPlus:{} },
    {name: {EN: 'Vegetables', FR: 'Légumes'}, label: {EN: '', FR: ''}, id2: 'V', expiration: '12', expirationMinusPlus:{DRAW: '-6'}},
    {name: {EN: 'Fruits', FR: 'Fruits'}, label: {EN: '', FR: ''}, id2: 'F', expiration: '12', expirationMinusPlus:{DRAW: '-6'}},
    {name: {EN: 'Soup', FR: 'Soupe'}, label: {EN: '', FR: ''}, id2: 'S', expiration: '3', expirationMinusPlus:{}},
    {name: {EN: 'Dish', FR: 'Plat'}, label: {EN: '', FR: ''}, id2: 'P', expiration: '3', expirationMinusPlus:{}},
    {name: {EN: 'Meat', FR: 'Viande'}, label: {EN: '', FR: ''}, id2: 'M', expiration: '1', expirationMinusPlus:{DCOO: '+3', DPOU: '+2', DPOR: '+2', DBEE: '+4'}},
    {name: {EN: 'Fish', FR: 'Poisson'}, label: {EN: '', FR: ''}, id2: 'H', expiration: '2', expirationMinusPlus:{}},
    {name: {EN: 'Desert', FR: 'Dessert'}, label: {EN: '', FR: ''}, id2: 'D', expiration: '2', expirationMinusPlus:{}},
    {name: {EN: 'Ice cream', FR: 'Glace'}, label: {EN: '', FR: ''}, id2: 'I', expiration: '4', expirationMinusPlus:{}},
  ],
  details:[
    {name: {EN: 'Homemade', FR: 'Fait maison'}, label: {EN: '', FR: ''}, id2: 'DHOM', parents:['all'] },
    {name: {EN: 'Cooked', FR: 'Cuit'}, label: {EN: '', FR: ''}, id2: 'DCOO', parents:['V', 'S', 'M', 'P', 'H', 'F'] },
    {name: {EN: 'Raw', FR: 'Cru'}, label: {EN: '', FR: ''}, id2: 'DRAW', parents:['V', 'S', 'M', 'P', 'H', 'F'] },
    {name: {EN: 'White', FR: 'Blanc'}, label: {EN: '', FR: ''}, id2: 'DWHI', parents:['B'] },
    {name: {EN: 'Grey', FR: 'Gris'}, label: {EN: '', FR: ''}, id2: 'DGRE', parents:['B']},
    {name: {EN: 'Cereal', FR: 'Céréales'}, label: {EN: '', FR: ''}, id2: 'DCER', parents:['B']},
    {name: {EN: 'Cake', FR: 'Gateau'}, label: {EN: '', FR: ''}, id2: 'DCAK', parents:['D']},
    {name: {EN: 'Pie', FR: 'Tarte'}, label: {EN: '', FR: ''}, id2: 'DPIE', parents:['D']},
    {name: {EN: 'Vanilla', FR: 'Vanille'}, label: {EN: '', FR: ''}, id2: 'DVAN', parents:['D', 'I']},
    {name: {EN: 'Strawberry', FR: 'Fraise'}, label: {EN: '', FR: ''}, id2: 'DSTR', parents:['D', 'I']},
    {name: {EN: 'Chocolate', FR: 'Chocolat'}, label: {EN: '', FR: ''}, id2: 'DCHO', parents:['D', 'I']},
    {name: {EN: 'Poultry', FR: 'Volaille'}, label: {EN: '', FR: ''}, id2: 'DPOU', parents:['S', 'M', 'P']},
    {name: {EN: 'Beef', FR: 'Beuf'}, label: {EN: '', FR: ''}, id2: 'DBEE', parents:['S', 'M', 'P']},
    {name: {EN: 'Pork', FR: 'Porc'}, label: {EN: '', FR: ''}, id2: 'DPOR', parents:['S', 'M', 'P']},
    {name: {EN: 'Veal', FR: 'Veau'}, label: {EN: '', FR: ''}, id2: 'DVEA', parents:['M', 'P']},
    {name: {EN: 'Fish', FR: 'Poisson'}, label: {EN: '', FR: ''}, id2: 'DFIS', parents:['S', 'P']},
    {name: {EN: 'Vegetarian', FR: 'Végétarien'}, label: {EN: '', FR: ''}, id2: 'DVEG', parents:['S', 'P']},
  ],
  containers:[
      {name: {EN: 'Plastic box', FR: 'Boîte en plastique'}, label: {EN: 'ex: Tupperware', FR: 'ex: Tupperware'}, id2: 'P'},
      {name: {EN: 'Aluminium box', FR: 'Boîte en aluminium'}, label: {EN: 'ex: Doggy box', FR: 'ex: Boîte de restaurant'}, id2: 'A'},
      {name: {EN: 'Plastic bag', FR: 'Sac de congélation'}, label: {EN: 'ex: Ziplog', FR: 'ex: Ziplog'}, id2: 'B'},
      {name: {EN: 'Aluminium foil', FR: 'Papier Aluminium'}, label: {EN: '', FR: ''}, id2: 'F'},
  ],  
  colors:[
      {name: {EN: 'Transparent', FR: 'Transparent'}, label: {EN: '', FR: ''}, id2: 'T', parents:['P'] },
      {name: {EN: 'White', FR: 'Blanc'}, label: {EN: '', FR: ''}, id2: 'W', parents:['P']},
      {name: {EN: 'Blue', FR: 'Bleu'}, label: {EN: '', FR: ''}, id2: 'B', parents:['P']},
      {name: {EN: 'Green', FR: 'Vert'}, label: {EN: '', FR: ''}, id2: 'G', parents:['P']},
      {name: {EN: 'Red', FR: 'Rouge'}, label: {EN: '', FR: ''}, id2: 'R', parents:['P']},
      {name: {EN: 'Other', FR: 'Autre'}, label: {EN: '', FR: ''}, id2: 'O', parents:['P']},
  ],
  sizes:[
      {name: {EN: '1', FR: '1'}, label: {EN: '1 serving', FR: '1 portion'}, id2: '1'},
      {name: {EN: '+2', FR: '2+'}, label: {EN: '2 to 3 servings', FR: '2 à 3 portions'}, id2: '2'},
      {name: {EN: '+4', FR: '4+'}, label: {EN: '4 to 5 servings', FR: '4 à 5 portions'}, id2: '4'},
      {name: {EN: '+6', FR: '6+'}, label: {EN: '6 or more servings', FR: '6 portions ou plus'}, id2: '6'},
  ],  
  freezers:[
      {name: {EN: 'Kitchen', FR: 'Cuisine'}, label: {EN: 'Kitchen freezer', FR: 'Congélateur dans la cuisine'}, id2: 'K'},
      {name: {EN: 'Basement', FR: 'Cave'}, label: {EN: 'Basement freezer', FR: 'Congélateur à la cave'}, id2: 'B'},
      {name: {EN: 'Other', FR: 'Autre'}, label: {EN: 'Other freezer location', FR: 'Congélateur à un autre endroit'}, id2: 'O'},
  ],
  locations:[
      {name: {EN: 'Top', FR: 'Haut'}, label: {EN: 'Higher section', FR: 'Partie supérieure'}, id2: 'T'},
      {name: {EN: 'Middle', FR: 'Milieu'}, label: {EN: 'Middle section', FR: 'Partie centrale'}, id2: 'M'},
      {name: {EN: 'Bottom', FR: 'Bas'}, label: {EN: 'Lower section', FR: 'Partie inférieure'}, id2: 'B'},
  ]
};